# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Webdriver.io Cucumber tests

on:
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master", "github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 24.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './wdio/package-lock.json'
      - name: install dependencies
        run: npm ci
        working-directory: ./wdio
      - name: run wdio tests
        run: npm run wdio
        working-directory: ./wdio
      - uses: actions/upload-artifact@v6.0.0
        with:
          name: 'Allure Report'
          path: ./wdio/allure-report/